In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'C:\Users\User\Desktop\jupiter notebook\st.csv', sep=',')
df.tail(20)

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
166,21,161,36,3,2001,12,91,18,0,0,...,240,Милки Вей,800000.0,Педагогический,Педагогический,нет ни брата ни сестры,У прохода,5,15.0,40.0
167,21,168,40,4,2001,100,91,45,0,0,...,200,Натс,2.6,Экономический,СоцГум,нет ни брата ни сестры,У прохода,6,10.0,30.0
168,22,161,38,7,2000,50,91,74,0,0,...,1800,Натс,850000.0,Математический и ИТ,Другое,есть брат,У окна (пардон: у иллюминатора),5,13.0,35.0
169,21,160,37,4,2001,221,94,76,0,0,...,0,Сникерс,800000.0,Педагогический,Экономический,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,32.0
170,22,168,38,4,2000,49,100,56,0,0,...,240,КитКат,500000.0,Педагогический,Экономический,нет ни брата ни сестры,У окна (пардон: у иллюминатора),10,5.0,20.0
171,20,162,37,2,2002,70,82,0,0,0,...,540,Твикс,900.0,СоцГум,Юридический,есть сестра,У прохода,4,11.0,25.0
172,21,164,37,4,2000,260,86,0,0,0,...,60,Милки Вей,900000.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),10,6.0,30.0
173,29,176,39,7,1992,233,72,69,0,0,...,60,Сникерс,850000.0,Математический и ИТ,Экономический,есть сестра,У окна (пардон: у иллюминатора),7,11.0,30.0
174,20,158,37,3,2001,21,91,56,0,0,...,120,Милки Вей,700000.0,Математический и ИТ,Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У прохода,9,10.0,35.0
175,18,176,38,2,2003,183,90,0,0,0,...,240,Марс,854627.0,Естественный (биология-химия-физика-технари),СоцГум,есть сестра,У окна (пардон: у иллюминатора),16,13.0,28.0
176,21,162,38,7,2000,150,89,0,0,0,...,300,Твикс,800000.0,СоцГум,СоцГум,есть и брат и сестра,У окна (пардон: у иллюминатора),13,12.0,40.0
177,23,155,36,6,1999,90,91,51,0,0,...,100,Баунти,900000.0,Математический и ИТ,Математический и ИТ,есть сестра,У окна (пардон: у иллюминатора),5,4.0,3.0
178,21,170,39,4,2001,123,76,0,0,0,...,360,Сникерс,800000.0,СоцГум,Юридический,есть и брат и сестра,У окна (пардон: у иллюминатора),3,2.0,7.0
179,20,176,42,3,2001,80,85,0,0,0,...,120,Сникерс,700000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),5,5.0,20.0
180,21,167,36,4,2000,120,98,56,0,0,...,120,Твикс,8000000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,5.0,25.0
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [5]:
df.describe()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Height of 5000 mm,Width of 5000 mm,Putin age,Hair length,Floor number,Social network duration min,City population,MIddle and index finger,Middle and ring finger,Middle and little finger
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,...,186.000000,186.000000,186.000000,186.000000,186.000000,1.860000e+02,1.860000e+02,186.000000,186.000000,186.000000
mean,20.688172,170.661290,39.715054,3.500000,1991.107527,374.032258,81.634409,58.177419,13.182796,32.801075,...,75.720430,177.688172,690.236559,34.365054,6.322581,5.417500e+08,7.946669e+05,9.741935,9.705376,28.798925
std,3.468713,9.055881,2.814920,3.147285,132.099550,2199.541507,14.325019,29.575478,26.414552,38.992282,...,107.747088,240.978320,7360.321689,25.672211,4.338791,7.332267e+09,6.093052e+05,4.385241,6.894963,19.710011
min,17.000000,153.000000,34.000000,0.000000,200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,42.000000,0.200000,1.000000,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000
25%,19.000000,164.000000,38.000000,2.000000,2000.000000,74.500000,76.000000,50.000000,0.000000,0.000000,...,50.000000,100.000000,67.000000,12.000000,3.000000,1.200000e+02,7.000000e+05,7.000000,6.000000,20.000000
50%,20.000000,169.000000,39.000000,3.000000,2001.500000,130.000000,85.000000,70.000000,0.000000,0.000000,...,60.000000,140.000000,69.000000,30.000000,5.000000,2.000000e+02,8.000000e+05,10.000000,10.000000,28.500000
75%,21.000000,178.000000,42.000000,4.000000,2003.000000,236.000000,91.000000,76.750000,0.000000,75.000000,...,70.000000,167.250000,70.000000,50.000000,8.000000,3.600000e+02,8.845000e+05,12.000000,12.000000,35.000000
max,55.000000,197.000000,48.000000,37.000000,2004.000000,30000.000000,100.000000,100.000000,97.000000,98.000000,...,950.000000,1800.000000,100000.000000,150.000000,20.000000,1.000000e+11,8.000000e+06,30.000000,80.000000,250.000000

In [6]:
df['Growth'].mean()

170.66129032258064

In [7]:
df.Growth.median()

169.0

In [8]:
df_new = df[['Age','Growth','Weight']]

In [9]:
df_new

     Age  Growth  Weight
0     20     170    64.0
1     22     191    73.0
2     21     172    60.0
3     19     168    59.0
4     23     159    57.0
..   ...     ...     ...
181   23     168    59.0
182   19     169    43.0
183   18     161    51.0
184   19     169    62.0
185   18     164    54.0

[186 rows x 3 columns]

In [10]:
df['Weight'].describe()

count    157.000000
mean      64.031847
std       16.502300
min        3.000000
25%       53.000000
50%       60.000000
75%       71.000000
max      120.000000
Name: Weight, dtype: float64

In [11]:
df['Rock paper scissors'].value_counts()

Rock paper scissors
Ножницы    88
Камень     60
Бумага     38
Name: count, dtype: int64

In [12]:
df.iloc[9:10][["Sex",'Weight']]

       Sex  Weight
9  женский    58.0

In [13]:
df

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [14]:
df[df['Growth']>df['Growth'].mean()]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,21,175,43,5,2000,400,89,0,0,0,...,240,Сникерс,700000.0,Педагогический,Юридический,есть и брат и сестра,У окна (пардон: у иллюминатора),8,3.0,19.0
160,19,180,41,1,2003,250,90,90,95,0,...,120,Милки Вей,1000000.0,Математический и ИТ,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,6.0,13.0
173,29,176,39,7,1992,233,72,69,0,0,...,60,Сникерс,850000.0,Математический и ИТ,Экономический,есть сестра,У окна (пардон: у иллюминатора),7,11.0,30.0
175,18,176,38,2,2003,183,90,0,0,0,...,240,Марс,854627.0,Естественный (биология-химия-физика-технари),СоцГум,есть сестра,У окна (пардон: у иллюминатора),16,13.0,28.0
179,20,176,42,3,2001,80,85,0,0,0,...,120,Сникерс,700000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),5,5.0,20.0

In [15]:
df['Growth'].mean()

170.66129032258064

In [16]:
mw = df['Weight'].max()

In [17]:
mw = df['Weight'].max()
df[df['Weight'] == mw]['Growth']

7    180
Name: Growth, dtype: int64

In [18]:
army_persons = df[df['Army']=='могут призвать']
free_persons = df[df['Army']=='не призовут (по разным причинам)']
free_persons

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [19]:
free_persons['Hair length'].mean()

40.15570469798658

In [20]:
army_persons['Hair length'].mean()

11.045945945945945

In [21]:
f = df[['Friend number','Sex']]
f[f['Friend number']==0]

     Friend number      Sex
6                0  мужской
182              0  женский

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [23]:
dog_love = df[df['Animal']=='Собак']
dog_love['Animal'].value_counts()

Animal
Собак    60
Name: count, dtype: int64

In [24]:
df2 = dog_love[dog_love['Floor number'] ==1]
df2['Floor number']

6      1
26     1
61     1
72     1
128    1
153    1
183    1
Name: Floor number, dtype: int64

In [25]:
df2['Floor number'].value_counts()

Floor number
1    7
Name: count, dtype: int64

In [26]:
7/60*100

11.666666666666666

In [32]:
df_cut = df[['Age','Growth','Weight']]
df_cut.head()

   Age  Growth  Weight
0   20     170    64.0
1   22     191    73.0
2   21     172    60.0
3   19     168    59.0
4   23     159    57.0

In [37]:
df_cut.sort_values(by=['Age','Growth'], ascending = [False,True])

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
112   18     183    65.0
16    18     185    64.0
42    18     185    68.0
126   17     168    71.0
115   17     175    72.0

[186 rows x 3 columns]

In [42]:
df_sorted = df_cut.sort_values(by='Growth', ascending = False)
df_sorted.iloc[2,2]

73.0

In [45]:
df_cut['Mass Index'] = 10**4*df_cut['Weight']/(df_cut['Growth']**2)

C:\Temp\ipykernel_10924\3534804649.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cut['Mass Index'] = 10**4*df_cut['Weight']/(df_cut['Growth']**2)

In [46]:
df_cut

     Age  Growth  Weight  Mass Index
0     20     170    64.0   22.145329
1     22     191    73.0   20.010416
2     21     172    60.0   20.281233
3     19     168    59.0   20.904195
4     23     159    57.0   22.546576
..   ...     ...     ...         ...
181   23     168    59.0   20.904195
182   19     169    43.0   15.055495
183   18     161    51.0   19.675167
184   19     169    62.0   21.707923
185   18     164    54.0   20.077335

[186 rows x 4 columns]

In [51]:
df_cut.sort_values(by='Mass Index', ascending=True)

     Age  Growth  Weight  Mass Index
81    55     160     3.0    1.171875
114   22     178     7.0    2.209317
182   19     169    43.0   15.055495
5     18     177    50.0   15.959654
139   20     170    47.0   16.262976
..   ...     ...     ...         ...
158   21     168     NaN         NaN
161   24     163     NaN         NaN
167   21     168     NaN         NaN
170   22     168     NaN         NaN
178   21     170     NaN         NaN

[186 rows x 4 columns]

In [52]:
df_cut.corr()

                 Age    Growth    Weight  Mass Index
Age         1.000000 -0.101982 -0.185722   -0.200305
Growth     -0.101982  1.000000  0.544528    0.146201
Weight     -0.185722  0.544528  1.000000    0.904678
Mass Index -0.200305  0.146201  0.904678    1.000000

In [54]:
df.groupby('Sex')[['Growth','Weight']].mean()

             Growth     Weight
Sex
женский  165.725000  59.105263
мужской  179.636364  71.580645

In [60]:
df.groupby(['Sex','Chocolate'])[['Russian rating','Maths rating']].mean()

                                           Russian rating  Maths rating
Sex     Chocolate
женский M&Ms                                    79.400000     51.600000
        Баунти                                  81.181818     56.318182
        КитКат                                  85.782609     61.782609
        Марс                                    91.166667     36.666667
        Милки Вей                               79.583333     45.250000
        Натс                                    84.636364     53.818182
        Скиттлс (хотя это и не шоколадка)       86.000000     67.000000
        Сникерс                                 80.375000     61.562500
        Твикс                                   86.478261     55.217391
мужской M&Ms                                    83.666667     76.666667
        Баунти                                  78.375000     68.000000
        КитКат                                  74.416667     51.083333
        Марс                                    85.600000     55.400000
        Милки Вей                               72.800000     61.800000
        Натс                                    70.500000     72.000000
        Скиттлс (хотя это и не шоколадка)       84.000000     77.000000
        Сникерс                                 77.666667     59.055556
        Твикс                                   79.818182     75.000000

In [62]:
df.groupby('Chocolate')[['Russian rating','Maths rating']].mean()

                                   Russian rating  Maths rating
Chocolate
M&Ms                                    81.000000     61.000000
Баунти                                  80.433333     59.433333
КитКат                                  81.885714     58.114286
Марс                                    88.636364     45.181818
Милки Вей                               77.588235     50.117647
Натс                                    82.461538     56.615385
Скиттлс (хотя это и не шоколадка)       85.000000     72.000000
Сникерс                                 78.941176     60.235294
Твикс                                   84.323529     61.617647

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [67]:
df_cut = df[['Year of birth','Growth','Weight','Hair length','Shoe size']]
df_cut

     Year of birth  Growth  Weight  Hair length  Shoe size
0             2002     170    64.0         50.0         40
1             2000     191    73.0          7.0         43
2             2000     172    60.0          4.0         41
3             2003     168    59.0         20.0         38
4             1998     159    57.0         55.0         36
..             ...     ...     ...          ...        ...
181           1999     168    59.0         30.0         39
182           2003     169    43.0         45.0         38
183           2003     161    51.0         40.0         37
184           2003     169    62.0        150.0         41
185           2003     164    54.0         60.0         39

[186 rows x 5 columns]

In [79]:
df_cut.sort_values('Shoe size')
df_cut.sort_values(by=['Shoe size','Growth'], ascending=[False,True]).head(10)

     Year of birth  Growth  Weight  Hair length  Shoe size
7             2003     180   120.0         20.0         48
27            2003     193    61.0          3.0         48
8             2002     185    69.0         25.0         46
103           2002     197   100.0         23.0         46
55            1999     180    92.0          0.2         45
76            2002     184     NaN         20.0         45
145           1999     184    92.0         45.0         45
16            2003     185    64.0          4.0         45
20            2001     186    93.0         20.0         45
24            2002     177    65.0         12.0         44

In [92]:
df_cut['Full length'] = df_cut['Growth'] + df_cut['Hair length']

C:\Temp\ipykernel_10924\542438141.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cut['Full length'] = df_cut['Growth'] + df_cut['Hair length']

In [93]:
df_cut.describe()

,Year of birth,Growth,Weight,Hair length,Shoe size,Full length
count,186.000000,186.000000,157.000000,186.000000,186.000000,186.000000
mean,1991.107527,170.661290,64.031847,34.365054,39.715054,205.026344
std,132.099550,9.055881,16.502300,25.672211,2.814920,21.983827
min,200.000000,153.000000,3.000000,0.200000,34.000000,170.000000
25%,2000.000000,164.000000,53.000000,12.000000,38.000000,187.250000
50%,2001.500000,169.000000,60.000000,30.000000,39.000000,201.000000
75%,2003.000000,178.000000,71.000000,50.000000,42.000000,217.750000
max,2004.000000,197.000000,120.000000,150.000000,48.000000,319.000000

In [94]:
df_cut.corr()

,Year of birth,Growth,Weight,Hair length,Shoe size,Full length
Year of birth,1.000000,-0.113357,0.006042,0.095402,-0.108360,0.064713
Growth,-0.113357,1.000000,0.544528,-0.554408,0.863252,-0.235492
Weight,0.006042,0.544528,1.000000,-0.319416,0.591149,-0.145316
Hair length,0.095402,-0.554408,-0.319416,1.000000,-0.567568,0.939398
Shoe size,-0.108360,0.863252,0.591149,-0.567568,1.000000,-0.307190
Full length,0.064713,-0.235492,-0.145316,0.939398,-0.307190,1.000000

In [98]:
df_glass = df.groupby('Glasses')[['Russian rating','Maths rating']].mean()
df_glass

                                     Russian rating  Maths rating
Glasses
да                                        83.388235     56.741176
нет                                       80.471910     59.955056
простите. не увидел(а) вопроса ))))       77.900000     54.700000

In [101]:
df_game = df.groupby('Rock paper scissors')[['Russian rating','Maths rating']].mean()
df_game

                     Russian rating  Maths rating
Rock paper scissors
Бумага                    76.473684     52.894737
Камень                    81.450000     62.166667
Ножницы                   83.988636     57.738636